In [30]:
import pandas as pd
import numpy as np

In [31]:
data = pd.read_csv("healthcare_dataset.csv")

In [32]:
data.head(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [33]:
data.shape

(55500, 15)

In [34]:
data.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [35]:
data.groupby('Name').agg(Nb=('Name', 'count')).reset_index().sort_values(['Nb'], ascending=False)

                      Name  Nb
5835           DAvId muNoZ   3
26446         allIsON cOok   2
31796          davId ADams   2
43208  mr. bRyCe gutierReZ   2
7616           ERiC NEWtOn   2
...                    ...  ..
17645        MiCHAEL EStES   1
17646       MiCHAEL MOsley   1
17647        MiCHAEL MoRSE   1
17648        MiCHAEL drAKE   1
49991         zachary WALl   1

[49992 rows x 2 columns]

In [36]:
data[data['Name'] == "DAvId muNoZ"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
2491,DAvId muNoZ,31,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive
46648,DAvId muNoZ,19,Male,A-,Cancer,2022-08-04,Jamie Gonzales,Olsen-Thomas,Blue Cross,32454.950609,406,Urgent,2022-08-17,Aspirin,Inconclusive
53672,DAvId muNoZ,28,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive

In [37]:
data_filtered = data.loc[:,['Name','Age','Gender','Blood Type']]

In [38]:
data_filtered[data_filtered.duplicated()]

                     Name  Age  Gender Blood Type
50023        Samuel joYCe   56    Male         O+
50040    KIMBErly vasqueZ   26    Male         A-
50055      SCoTT tHOrNton   55  Female         B-
50070         wiLliam LEe   27  Female         O+
50078  chRistOPheR NoRrIs   38    Male        AB-
...                   ...  ...     ...        ...
55461      connOR coMPTon   63    Male         A+
55462       alYSsA mIlLER   35  Female         A-
55464        ChRIs huGHeS   35  Female        AB-
55484     keNNEtH alvarez   80    Male         O+
55491       lInDA grIFfin   47  Female         O+

[534 rows x 4 columns]

In [39]:
data[data['Name'] == "Samuel joYCe"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
6319,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive

In [40]:
data = data.drop_duplicates()

# --- Notes pour data cleaning ---

1. supprimer les doublons
2. Mettre en capital la colonne "Name"
3. Arrondir à deux décimales la colonne "Billing Amount"
4. Convertir en date les colones "Date of Admission" et "Discharge Date"

# --- Notes pour structure du schéma de base de données ---

index : [Name, Date of Admission, Medical Condition]

# --- Structure de la base de données ---

[
  {
    "id": {
      "personalInfos": {
        "firstName": "firstName",
        "lastName": "lastName",
        "gender": "gender",
        "age": "age",
        "bloodType": "bloodType"
      },
      "admissions": [
        {
          "admissionId": "admissionId",
          "dateOfAdmission": "dateOfAdmission",
          "admissionType": "admissionType",
          "roomNumber": "roomNumber",
          "medicalCondition": ["medicalCondition"],
          "medication": ["medication"],
          "testResults": ["testResults"],
          "doctor": "doctor",
          "hospital": "hospital",
          "billingInfos": {
            "insuranceProvider": "insuranceProvider",
            "dischargeDate": "dischargeDate",
            "billingAmount": "billingAmount"
          }
        }
      ]
    }
  }
]

In [41]:
data_head_5 = data.head(5)

In [42]:
data_head_5

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [43]:
col_name = data_head_5.columns.to_list()
new_col_name = list(map(lambda x: x.replace(" ", "_"), col_name))
new_col_name = list(map(lambda x: x.lower(), new_col_name))
data_head_5.columns = new_col_name

In [44]:
data_head_5

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [45]:
new_col_name

['name',
 'age',
 'gender',
 'blood_type',
 'medical_condition',
 'date_of_admission',
 'doctor',
 'hospital',
 'insurance_provider',
 'billing_amount',
 'room_number',
 'admission_type',
 'discharge_date',
 'medication',
 'test_results']

In [47]:
data["Name"] =  data["Name"].str.upper()

In [48]:
data['Name'].unique().tolist()

['BOBBY JACKSON',
 'LESLIE TERRY',
 'DANNY SMITH',
 'ANDREW WATTS',
 'ADRIENNE BELL',
 'EMILY JOHNSON',
 'EDWARD EDWARDS',
 'CHRISTINA MARTINEZ',
 'JASMINE AGUILAR',
 'CHRISTOPHER BERG',
 'MICHELLE DANIELS',
 'AARON MARTINEZ',
 'CONNOR HANSEN',
 'ROBERT BAUER',
 'BROOKE BRADY',
 'MS. NATALIE GAMBLE',
 'HALEY PERKINS',
 'MRS. JAMIE CAMPBELL',
 'LUKE BURGESS',
 'DANIEL SCHMIDT',
 'TIMOTHY BURNS',
 'CHRISTOPHER BRIGHT',
 'KATHRYN STEWART',
 'DR. EILEEN THOMPSON',
 'PAUL HENDERSON',
 'PETER FITZGERALD',
 'CATHY SMALL',
 'MR. KENNETH MOORE',
 'MARY HUNTER',
 'JOSHUA OLIVER',
 'THOMAS MARTINEZ',
 'JAMES PATTERSON',
 'WILLIAM COOPER',
 'ERIN ORTEGA',
 'NICOLE RODRIGUEZ',
 'DAVID ANDERSON',
 'DENISE TORRES',
 'CASSANDRA ROBINSON',
 'NICOLE LUCERO',
 'PAMELA FERNANDEZ',
 'CHRISTOPHER LEE',
 'THOMAS MORSE',
 'MR. ERIC LANE',
 'KATHERINE SMITH',
 'PAUL WILLIAMS',
 'LYNN MARTINEZ',
 'CHRISTOPHER CHAPMAN',
 'CHRIS FRYE',
 'KYLE BENNETT',
 'BRANDON COLLINS',
 'MICHAEL LIU',
 'STEPHANIE KENT',
 'JESSE BANKS',
 'PEGGY LEE',
 'TAMARA HERNANDEZ',
 'MR. DAVID PIERCE MD',
 'BETHANY MOORE',
 'MICHAEL MILLS',
 'KYLE WILEY',
 'JACQUELINE JORDAN',
 'ASHLEY GUTIERREZ',
 'KIM SCOTT',
 'TRAVIS CARTER',
 'LARRY RODGERS',
 'NANCY GLOVER',
 'JESSICA KING',
 'CHRISTOPHER GONZALEZ',
 'JOHN HARTMAN',
 'MICHAEL MILLER',
 'ERICA MYERS',
 'CAROL PATTERSON',
 'JOSE LOPEZ',
 'KEVIN SIMMONS JR.',
 'DUANE HANEY',
 'JONATHAN YATES',
 'JOHN THOMAS',
 'ADRIAN BUCKLEY',
 'APRIL SANTIAGO',
 'DIANE SCHULTZ',
 'TIMOTHY MYERS',
 'NICOLE HUGHES',
 'CHAD MORENO',
 'SEAN JENNINGS',
 'DIANE BRANCH',
 'CINDY OROZCO',
 'PATRICIA MEDINA',
 'KAYLA PADILLA',
 'JUAN KLEIN',
 'WILLIAM HILL',
 'CARL BEST',
 'TINA GRIFFIN',
 'MR. TYLER TAYLOR PHD',
 'TAYLOR HOWELL DDS',
 'MICHAEL MARTIN',
 'HEATHER MILLER',
 'CATHERINE GARDNER',
 'ANNE THOMPSON',
 'TODD COOPER',
 'PHILLIP LYONS',
 'MARK FORD',
 'MARCUS ZAMORA',
 'KATIE HENRY',
 'WILLIAM MORTON',
 'KATRINA MARTIN',
 'HUNTER MCKAY',
 'DWAYNE DAVIS',
 'SARAH CALDWELL',
 'DAVID HIGGINS',
 'BRADLEY COMBS',
 'CHRISTINA SCHMITT',
 'COLTON STRONG',
 'MARK PRICE',
 'SUZANNE SCHNEIDER',
 'MICHAEL HURLEY',
 'LINDSEY LAMBERT',
 'REBECCA PARSONS',
 'JUDY JOHNSON',
 'TONYA CAMPBELL',
 'JAMES ROSS',
 'SARA COOK',
 'ANNE HOWELL',
 'RENEE BAILEY',
 'JEFFREY TURNER',
 'DR. LAUREN CLARK DDS',
 'TERRY THOMAS',
 'JASON BAKER',
 'JESSICA GUTIERREZ',
 'COURTNEY HODGES',
 'ANTHONY REYES',
 'LEAH CROSS DDS',
 'PAUL MARTINEZ',
 'DENISE RODRIGUEZ',
 'ASHLEY ERICKSON',
 'SEAN CARDENAS',
 'ALAN ALVAREZ',
 'JESSICA PHILLIPS',
 'TIMOTHY COLEMAN',
 'CHRISTINA WOODS',
 'MELISSA SCOTT',
 'GARY HOPKINS',
 'APRIL VALENCIA',
 'RITA ARCHER',
 'KIM PENA',
 'JASON FOLEY',
 'SHAUN GUZMAN',
 'MATTHEW WHITE',
 'ALEXIS WILSON',
 'JACQUELINE MARSHALL',
 'ROBERT HIGGINS',
 'SIERRA MORTON',
 'NATALIE STANTON',
 'JESSICA ACEVEDO',
 'JENNIFER MCMILLAN',
 'CHRISTOPHER MCCLAIN',
 'KEVIN HICKS',
 'MELINDA RICHARDS',
 'ROBYN MIRANDA',
 'SCOTT CASTILLO',
 'JOHN GARCIA',
 'MICHAEL TAYLOR',
 'JEFFREY WOOD',
 'MICHAEL SMITH',
 'WILLIAM GRIFFITH',
 'CHRISTINA LAWRENCE',
 'JESSICA HOLMES',
 'TRACEY GREENE',
 'AMANDA LOPEZ',
 'LAURA PETERS',
 'LAUREN ANDERSON',
 'WILLIAM CAMPOS',
 'JESSICA GONZALES',
 'BRUCE GONZALES',
 'ROBERT WALSH',
 'LISA LEWIS',
 'WILLIAM RUIZ',
 'STEVEN BALDWIN',
 'MEGAN COLON',
 'KIMBERLY BROOKS',
 'EDWARD SMITH JR.',
 'ALLISON CORDOVA',
 'LINDA THOMAS',
 'PARKER MOORE',
 'TANYA SOTO',
 'MICHAEL JORDAN',
 'CHRISTINA MARTIN',
 'TRACY BURKE',
 'DAVID SPENCE',
 'JOSEPH FOSTER',
 'NICHOLAS HALL',
 'CHRISTINA MACIAS',
 'SCOTT JONES',
 'JAMES ANDERSON',
 'SHAUN LONG',
 'KRISTINA MORA',
 'JOSHUA RICHMOND',
 'MARK LAWRENCE',
 'JOHN ELLIS',
 'MRS. TIFFANY DENNIS',
 'CYNTHIA HUANG',
 'MELISSA LAWRENCE',
 'STEVEN GOODWIN',
 'MARY HUNT',
 'ERIC RIVERA',
 'ALAN TAYLOR',
 'MICHAEL CAMPBELL',
 'ASHLEY WEBB DDS',
 'SHANNON BROWN',
 'LAWRENCE SHEPHERD',
 'SCOTT WADE',
 'HEATHER CURTIS',
 'KEVIN JEFFERSON',
 'DAVID GRIFFIN',
 'GRANT GEORGE',
 'ERIC STEWART',
 'ROBERT PITTMAN',
 'SYDNEY CROSS',
 'DAVID CRAWFORD',
 'LEAH DRAKE',
 'DIANA HALL',
 'JUSTIN LE',
 'KAREN PRICE DDS',
 'CAROLYN STEELE',
 'LAUREN RAMIREZ',
 'JACOB NEWMAN',
 'KATHERINE BARNETT',
 'JODI MARTINEZ',
 'ANDREA ALLEN',
 'NOAH BAXTER',
 'HECTOR MAXWELL',
 'HOLLY WALTERS',
 'JOSEPH SMITH',
 'ALBERT THOMAS',
 'JEFFERY WILLIAMSON',
 'JONATHAN MEADOWS',
 'KRISTIN BENNETT',
 'JOSEPH CARPENTER',
 'LARRY MAYER',
 'CLAYTON PETERSON',
 'DONALD ALVAREZ',
 'SARAH LEE',
 'JOHN PEREZ',
 'TIMOTHY JACOBS',
 'NATHAN SMALL',
 'DUSTIN WRIGHT',
 'JACOB WILLIAMS',
 'WILLIAM MCCOY',
 'DR. MATTHEW WILKINS',
 'JOSEPH GONZALEZ',
 'ROBERT FIELDS',
 'LAWRENCE MIRANDA',
 'MITCHELL CARROLL',
 'CODY NICHOLS',
 'KELLI THOMPSON',
 'DANIELLE LOPEZ',
 'MELINDA JONES',
 'KRISTIN SMITH',
 'STEPHANIE REYNOLDS',
 'ANNA NORMAN',
 'MARIA HAYES',
 'TONYA RILEY MD',
 'REGINA DUNN',
 'MICHAEL JACOBS',
 'JASON MOORE MD',
 'ERIC HALL',
 'MALIK MARTINEZ',
 'LISA KENNEDY',
 'KRISTIN OCHOA',
 'JOSEPH ZUNIGA',
 'KYLE TYLER',
 'ERIC DUNCAN',
 'RACHEL ROMERO',
 'MICHAEL ANDERSON',
 'EMILY CLARK',
 'DANIEL MCKINNEY',
 'BONNIE WILLIAMS',
 'MARCUS HENRY',
 'KATHERINE HART',
 'MICHELLE PIERCE',
 'JULIE MEJIA',
 'CAMERON SANCHEZ',
 'DAVID VINCENT',
 'MELISSA GOMEZ',
 'AMANDA PONCE',
 'CAROL GOMEZ',
 'CHRISTOPHER PALMER',
 'PAUL HAHN',
 'ASHLEY MOORE',
 'LINDA HAMILTON',
 'ROBIN COX',
 'ANTHONY HALL',
 'ROBERT SMITH',
 'DEREK CARTER',
 'HEATHER MAY',
 'PETER GONZALEZ',
 'CHRIS FLETCHER',
 'SHIRLEY WILKINSON',
 'COURTNEY FARRELL',
 'ANDREA WILLIS',
 'CHAD HUFF',
 'DEVIN GILBERT',
 'DONALD DAVIS',
 'KURT MURPHY',
 'SYLVIA WEST',
 'DONALD VAZQUEZ',
 'REBECCA RUSH',
 'CHRISTOPHER CURRY',
 'MICHAEL EDWARDS',
 'CHRISTOPHER ARNOLD',
 'RACHEL HICKMAN',
 'ASHLEY GRAY',
 'ELIZABETH PEREZ',
 'ANGEL RANDOLPH DDS',
 'MARK SAUNDERS',
 'CHRISTIAN LANG',
 'PAM PERKINS',
 'KAYLA GREENE',
 'MICHAEL DAVID',
 'ALEXIS MCCALL',
 'MR. BRANDON PEREZ MD',
 'DR. JEFFREY COLE',
 'MATTHEW BROWN',
 'ROBERT SEXTON',
 'ASHLEY VASQUEZ',
 'MICHELLE FLYNN',
 'STEVEN TRAN',
 'JAMES MILLER',
 'BONNIE HILL',
 'ANTHONY DAVIS',
 'DAVID SHEPPARD',
 'JODI LANG',
 'VANESSA TAYLOR',
 'WAYNE LYNCH',
 'YESENIA MCFARLAND',
 'KENNETH WILSON',
 'JILLIAN MARKS',
 'MICHELLE CRUZ DDS',
 'CLARENCE FORD JR.',
 'DONALD KANE',
 'ZACHARY LARSEN',
 'SHERYL MARTINEZ',
 'MR. NATHAN AVILA',
 'ANNE ANTHONY',
 'HOLLY LAMBERT',
 'JAMES RASMUSSEN',
 'SARAH CANNON',
 'MELINDA TANNER',
 'LAURIE JOSEPH',
 'STEPHANIE HUNTER',
 'GINA DAVIS',
 'CHRISTOPHER SHEA JR.',
 'MRS. SABRINA BALL',
 'JOYCE MCCORMICK',
 'DEVIN BELL',
 'ALLISON RAMIREZ',
 'LAURA ROMERO',
 'TONI FAULKNER',
 'PATRICIA TURNER',
 'NATHAN RAY',
 'RYAN SANCHEZ',
 'THOMAS DENNIS',
 'MR. TIMOTHY FLORES',
 'WENDY LEVINE',
 'NICOLE GONZALEZ',
 'MICHAEL ELLISON',
 'BRANDON DAVIS',
 'VANESSA GARCIA',
 'AUTUMN PECK',
 'NATHANIEL REYNOLDS',
 'JOYCE MOODY',
 'MARK FUENTES',
 'BRETT FERGUSON',
 'TRAVIS SIMMONS',
 'JEREMY FRYE',
 'CAMERON MILLER',
 'WILLIAM WILLIAMS DDS',
 'TRACIE WRIGHT',
 'DAVID REYES',
 'PAIGE KING',
 'JAMES GARCIA',
 'LORI HARVEY',
 'AMY WANG',
 'JORDAN VARGAS',
 'GORDON KELLY',
 'NATHAN SCOTT',
 'LISA GREEN',
 'AMY COMBS',
 'KELLY SANFORD',
 'MRS. JESSICA BLACK MD',
 'ROBERT GOULD',
 'CHRISTINE VARGAS',
 'BARBARA DIAZ',
 'JOHN WASHINGTON',
 'DEVIN STEWART',
 'JAMES ROBERTS',
 'JAMES YATES',
 'PETER NICHOLS',
 'KAREN PRICE',
 'CHRISTOPHER JONES',
 'LARRY LEONARD',
 'MICHELLE ZHANG',
 'KRISTEN FLORES',
 'MATTHEW BELL',
 'BRADLEY MIRANDA',
 'CHRISTOPHER MOORE',
 'DAN PINEDA',
 'MARIAH SMITH',
 'SABRINA COOK',
 'MELISSA HOFFMAN',
 'JOSEPH MARTIN',
 'MELISSA SIMS',
 'SARAH EVANS',
 'MARIA ANDERSON',
 'MARIA JOHNSTON',
 'JAMES COLE',
 'ISAIAH HOLT',
 'JOSEPH GONZALES',
 'JENNIFER CAMACHO',
 'HECTOR JONES',
 'JESSICA JONES DDS',
 'ISABELLA MARTIN',
 'DANIEL PALMER',
 'STEPHANIE BENSON',
 'ASHLEY WILLIAMS',
 'GREGORY NGUYEN',
 'JOE SMITH',
 'LISA WATTS',
 'ALEXANDER GARCIA',
 'ELIZABETH PERKINS',
 'LAURA WELLS',
 'ROBERT MCCORMICK',
 'MICHAEL YU',
 'JACOB GRAHAM',
 'ANDREA KENNEDY',
 'STACEY ANDERSON',
 'JASON MARSH',
 'TIFFANY FERGUSON',
 'MARK HERNANDEZ',
 'KEITH HENRY',
 'MICHELLE WRIGHT',
 'TROY DAVIS',
 'MISTY BURTON',
 'ROBERT ROBINSON',
 'CHRISTINA CALDERON',
 'JOHN GRAHAM',
 'MICHAEL PARKER',
 'WILLIAM EVANS',
 'VALERIE HODGES',
 'BRENDA BECK',
 'CHRISTINE DAVIS',
 'KEVIN DANIEL',
 'BRITTNEY WAGNER',
 'CRISTIAN BUCHANAN',
 'MICHAEL BRADY',
 'JORDAN LEON',
 'KATELYN CUNNINGHAM',
 'KRYSTAL MENDOZA',
 'ALEX RODRIGUEZ',
 'GEOFFREY BARKER',
 'ALEC MITCHELL',
 'JASON JORDAN',
 'PHILIP REYES',
 'AARON BRADSHAW',
 'ERICA FORD',
 'DR. KATIE BARRETT DVM',
 'JACOB YOUNG',
 'AMY RAMOS',
 'PATRICK MORALES',
 'SOPHIA CONWAY',
 'JAMES MOORE',
 'CHRISTOPHER COCHRAN',
 'ROBERT CARTER',
 'MORGAN NGUYEN',
 'NATHAN MONTOYA',
 'JOE BERRY PHD',
 'DANIEL ORTIZ',
 'MATTHEW CLARK',
 'JACQUELINE HARDY',
 'EMILY JOSEPH',
 'SARAH HICKS',
 'BRIANA ROSS',
 'MARY MCCULLOUGH',
 'BRIAN OSBORNE',
 'SUSAN WALTERS',
 'CATHERINE HARVEY',
 'CORY PIERCE',
 'JESUS JORDAN',
 'ANN DUNCAN',
 'SARAH PORTER',
 'JACQUELINE DEAN',
 'ANNE LAM',
 'JENNIFER GOMEZ',
 'DAVID CURTIS',
 'JOSHUA JOHNSON',
 'JEREMY BOWEN',
 'DENNIS CLARKE',
 'JENNIFER SPENCE',
 'BILLY FITZGERALD',
 'KRISTEN JAMES',
 'CAITLIN BENDER',
 'BRENDA FULLER',
 'CASSANDRA RICE',
 'SERGIO SANCHEZ',
 'KEVIN STEIN',
 'MAUREEN GRANT MD',
 'SAMANTHA GUTIERREZ',
 'GEORGE WOODWARD',
 'SHANE TATE',
 'KERRY HAWKINS',
 'MARISSA MORA',
 'RICKY MEYER',
 'EDWARD JONES JR.',
 'HEATHER MELENDEZ',
 'JESSICA MACIAS',
 'JAMIE LEACH',
 'MATTHEW SIMMONS',
 'SHEILA BAXTER',
 'DAVE PARRISH',
 'BRYAN STEWART',
 'JAMES BELL',
 'JOSHUA LOVE',
 'ROBERT CLARK',
 'MARISA GOLDEN',
 'NANCY HAMILTON',
 'BRYAN BOWERS',
 'NICOLE MARTIN',
 'WILLIAM HARMON',
 'TOM BROWN',
 'CYNTHIA NELSON',
 'TODD GROSS',
 'STEPHANIE CHUNG',
 'KAYLA PEREZ',
 'JOSHUA NELSON',
 'JAKE COPELAND',
 'MARIA GARDNER',
 'JANET ROBERTS DDS',
 'PETER RAMSEY',
 'ASHLEY FARMER',
 'KATHERINE HALE',
 'GARY BOWEN',
 'LAURA RYAN',
 'TIMOTHY LOPEZ',
 'ANTHONY GUZMAN',
 'MICHAEL SHARP',
 'DAVID CARROLL',
 'CONNOR BARTON',
 'ANGELA SCOTT',
 'DAVID ORTIZ',
 'PATRICK PIERCE',
 'KEITH JOHNSON',
 'ANTONIO SMITH',
 'JOHN TAYLOR',
 'BARBARA STEWART',
 'LARRY TANNER',
 'MALLORY DIAZ',
 'JOHN WILLIAMS',
 'PETER MILLER',
 'RYAN BUTLER',
 'SAMANTHA LOWERY',
 'TIFFANY LEE',
 'SAMANTHA WILLIS',
 'PAMELA BROWN',
 'CARLA WALKER',
 'MARY GONZALES',
 'SHELLEY FLEMING',
 'MARK BLAKE',
 'SCOTT KING',
 'JESSICA DAVIS',
 'ANTHONY ODOM',
 'CHARLES BROWN',
 'RACHEL DAVIS',
 'SANDRA MCCALL',
 'NICOLE FRANCIS',
 'STEVEN SMITH',
 'KAREN JOHNSON',
 'ANNA ROGERS',
 'PRISCILLA DECKER',
 'TREVOR WRIGHT',
 'WILLIAM TUCKER',
 'JESSICA KELLER',
 'WILLIAM HENRY',
 'ROBIN CLARKE',
 'JESSICA GARZA',
 'JAMIE SALAZAR',
 'STEVEN VAUGHAN',
 'MICHAEL CONTRERAS',
 'ALLEN ROBERTS',
 'AMY POWELL',
 'KENNETH SMITH',
 'MATTHEW WEST',
 'ERIK MONTOYA',
 'AUSTIN LEWIS',
 'KENNETH THOMPSON',
 'AMANDA DURHAM',
 'STEPHEN HUDSON',
 'CASSANDRA VELAZQUEZ',
 'SUSAN PENA',
 'ANTHONY PERKINS',
 'KATRINA LOPEZ',
 'BRIAN FOSTER',
 'JASON THOMPSON',
 'DAVID AYALA',
 'JARED YODER',
 'GREGORY CANNON',
 'LISA ANDERSON',
 'ELIZABETH SHIELDS',
 'PATRICIA KIM',
 'JESSICA SOTO',
 'JENNY REYNOLDS',
 'SHANNON BARRETT',
 'TERRI PERRY',
 'JOSEPH MADDEN',
 'REBECCA HOGAN',
 'KELLY WALKER',
 'JULIA MUELLER',
 'KAYLA MOORE',
 'KAITLYN SMITH',
 'DANIEL KEMP',
 'LAURA MYERS',
 'CAROL REED',
 'JESSICA CARTER',
 'VANESSA SCHAEFER',
 'MIGUEL GOMEZ',
 'LINDA CARDENAS',
 'ANNETTE JAMES',
 'SUSAN HURLEY',
 'CAROLYN WADE',
 'ANGELA DELEON',
 'CAROLYN COOPER',
 'REBECCA HARRIS',
 'GARY CURTIS',
 'RYAN LIU',
 'DENNIS MORROW',
 'JENNIFER COOPER',
 'JACOB LOPEZ',
 'CAROL MCCLAIN',
 'MICHAEL RICHARDSON',
 'MARK NGUYEN',
 'ERIC COOK',
 'KRISTEN STEPHENS',
 'DANA WALTON',
 'SCOTT ARNOLD',
 'MEGAN WHEELER',
 'AARON COX',
 'CASSANDRA MARTINEZ',
 'SHAWN BROWN',
 'SANDRA WILLIAMSON',
 'JENNIFER STEPHENS',
 'STEPHANIE RODRIGUEZ',
 'CAROLINE MCINTYRE',
 'MR. CAMERON ROBINSON',
 'TAMMY PINEDA',
 'NATALIE ANDERSON',
 'JASMINE RODRIGUEZ',
 'DEBRA MCKEE',
 'SANDRA GREENE',
 'CRYSTAL MORRIS',
 'JASON PARKER',
 'ROY JONES',
 'RICHARD ANDERSON',
 'JENNIFER FOSTER',
 'DEBBIE WILSON',
 'TRAVIS FLORES',
 'EMILY YOUNG',
 'SANDY HALL',
 'MADISON WRIGHT',
 'AMY MANN',
 'JASON STEELE',
 'PAMELA MIDDLETON',
 'LISA JACKSON',
 'SAMANTHA PATEL',
 'HERBERT RODRIGUEZ',
 'OLIVIA POWELL',
 'SAMANTHA PERKINS',
 'MICHAEL POTTS',
 'KERRY HERNANDEZ',
 'JOSHUA REYES',
 'JENNIFER ORTEGA',
 'BRITTANY BRAUN',
 'DANIEL CHEN',
 'ERICA HART',
 'ALICIA SCOTT',
 'AMANDA AGUIRRE',
 'MARK HICKS',
 'TIMOTHY DAVIS',
 'LONNIE DOMINGUEZ',
 'KIMBERLY HALE',
 'DANA WILLIAMSON',
 'MR. GEORGE BROWN JR.',
 'ALLEN CAMACHO',
 'NATHAN WOODS',
 'CATHERINE SMITH',
 'JERRY LEE',
 'ALEXANDER COLEMAN',
 'DAVID JENSEN',
 'DEBORAH EVANS',
 'ALEXANDRIA COLON',
 'SAMUEL HANSON',
 'BRYAN PHILLIPS',
 'NATHAN WILEY',
 'ALISHA MURPHY',
 'AMANDA LUCERO',
 'SHEILA SELLERS',
 'SUSAN CHAN',
 'ANGEL MITCHELL',
 'DARLENE COHEN',
 'KRISTY ONEILL',
 'SHERRI GARCIA',
 'MICHAEL WEBER',
 'BETH SCHWARTZ',
 'CYNTHIA CLARKE',
 'MARK GILES',
 'TAMARA BELTRAN',
 'JOSEPH GUTIERREZ',
 'JAMIE JIMENEZ',
 'CHARLES MURPHY',
 'CARLOS LOPEZ',
 'JOHNNY IRWIN',
 'SCOTT WERNER',
 'TERRI STEWART',
 'DAVID DAVIS',
 'STEPHEN HARRIS',
 'BRIDGET ADAMS',
 'MICHAEL MORTON',
 'MICHELLE LIU',
 'REGINA BRIGHT',
 'SAMUEL DECKER',
 'PAUL WRIGHT',
 'BRIAN OLSON',
 'TRACEY HARRISON',
 'ERIKA JOHNSON',
 'PETER CUNNINGHAM',
 'SIERRA WHITE',
 'EDDIE RUSSO DVM',
 'YVETTE TURNER',
 'JAMES CHARLES',
 'ALEXIS ALLEN',
 'STEPHANIE MARTIN',
 'SHELBY ANDERSON',
 'ABIGAIL FARMER',
 'CHRISTINA MILLER',
 'MATTHEW WYATT',
 'DAVID MONTOYA',
 'ERIC PARK',
 'LORI TREVINO',
 'DWAYNE CASTILLO',
 'KRISTINE MCCALL',
 'JOSEPH SELLERS',
 'DR. DONALD ANDERSON',
 'VICTORIA WILLIAMS',
 'ANNA JONES',
 'MR. ROBERT DAVIS',
 'JEFFREY HALL',
 'TERRY GRAVES',
 'JEROME MORALES',
 'KEITH RODRIGUEZ',
 'TAMARA DAVENPORT',
 'JONATHAN SIMON',
 'HOLLY ARMSTRONG',
 'RONALD BANKS',
 'RYAN BRADFORD DDS',
 'JANICE HALL',
 'JACOB MCDONALD',
 'GLENN MASSEY',
 'SANDRA MURRAY',
 'MARK WILLIAMS',
 'STEPHANIE REID DVM',
 'SETH BARTLETT II',
 'JEREMY RICH',
 'ELIZABETH MILLER',
 'ERIN MARTIN',
 'FRANK HESS',
 'PAUL ROGERS',
 'JENNIFER EDWARDS',
 'BRIAN HALL',
 'KIMBERLY WILLIAMS',
 'ISAAC MENDEZ',
 'SARAH SMITH',
 'DANIEL WOLF',
 'ROBERT ROSS',
 'DOUGLAS FOSTER',
 'LOUIS LOWERY',
 'JESSICA TYLER',
 'WILLIAM DAVIES',
 'JESSICA REYES',
 'DANIEL JONES',
 'PAULA MORALES',
 'DAVID SPEARS',
 'SCOTT BERRY',
 'DALTON NGUYEN',
 'SCOTT CLARK',
 'JAMIE BAKER',
 'COURTNEY PATRICK',
 'WILLIAM WARE',
 'AMBER ANDERSON',
 'CASEY JOHNSON',
 'ZACHARY COLLINS',
 'ZACHARY REED',
 'CHRISTOPHER WEISS',
 'CHARLES STRONG',
 'KATHERINE KELLY',
 'CHRISTOPHER HENDERSON',
 'JOSEPH BROWN',
 'JOSEPH SANCHEZ',
 'KYLE PEREZ',
 'EDUARDO HOUSTON',
 'LORI ROACH',
 'ERIC BUTLER',
 'JEFFREY BROWN',
 'THOMAS HAAS',
 'KELLY TURNER',
 'LANCE SIMPSON',
 'JEFFREY GREEN',
 'ERIC COLLINS',
 'BRIANNA WILLIAMS',
 'ROBERT GRAVES',
 'CINDY WILLIAMS',
 'VICTOR SULLIVAN',
 'FRANK SCOTT',
 'MARK BRADSHAW',
 'JESSICA DUNN',
 'KELSEY FOX',
 'MARY RICE',
 'RACHEL JACKSON',
 'LEAH FREDERICK',
 'CONNOR ODONNELL',
 'CLAUDIA DOWNS',
 'WILLIAM LANG',
 'LISA MORAN',
 'RUBEN BURTON',
 'BRANDON SMITH',
 'JESSICA MURPHY',
 'MISTY WILLIAMS',
 'BRANDY GEORGE',
 'ANDREA BUCK',
 'STEPHANIE BURKE',
 'STEPHANIE MOON',
 'SHARON JOHNSON',
 'MATTHEW HALEY',
 'SABRINA MAY',
 'MELINDA AUSTIN',
 'ANGELA MONTGOMERY',
 'VANESSA MARTIN',
 'GABRIEL STEVENS',
 'MICHAEL WOLFE',
 'BROOKE TORRES',
 'VICTOR DUKE',
 'JOSEPH GARRETT',
 'KARA LI',
 'JUAN KELLEY',
 'SHAWNA RUSSELL',
 'LORI LAWRENCE',
 'WHITNEY JONES',
 'JOE DAVILA',
 'LISA KELLER',
 'JORDAN BUSH',
 'BRENDA YU',
 'JASMINE SHORT',
 'TAMARA LEONARD',
 'KEVIN WONG',
 'LISA LOPEZ',
 'JUSTIN VARGAS',
 'JODY LOPEZ',
 'JONATHAN WOODS',
 'EMMA RAY',
 'ANDREA JOHNSON',
 'WAYNE SHARP',
 'SHELBY BLACK',
 'MARTHA MARTIN',
 'AMANDA WILSON',
 'JEREMY NGUYEN',
 'EILEEN HARRIS',
 'JOHN BECKER',
 'FELICIA WILEY',
 'JESSE JONES',
 'STEVEN GLENN',
 'CAROLINE SWANSON',
 'TERRY NICHOLSON',
 'KELLY THOMAS',
 'STEVEN MCGEE',
 'SHELLEY WARE',
 'MELISSA BRADY',
 'MARIA HALL',
 'ANDRE SMITH',
 'KAREN GONZALEZ',
 'VINCENT SELLERS',
 'BRANDON BURKE',
 'MR. MARK HANCOCK',
 'KENNETH PEREZ',
 'MARTIN HANSEN',
 'SUSAN BROWN',
 'NICOLE ALVARADO',
 'JESSICA RODRIGUEZ',
 'TINA PRICE',
 'MR. JACK WILLIS',
 'GREGORY ADAMS',
 'DAVID ROBERTS',
 'CORY PERRY',
 'JESSICA BARRY',
 'CYNTHIA THOMAS',
 'SHANNON JOHNSON',
 'JUSTIN WHITE',
 'REGINA STEWART',
 'CHELSEA FINLEY',
 'EMMA BENNETT',
 'ALAN LEE',
 'KATELYN MILLER',
 'AMANDA MORRIS',
 'DAVID PRATT',
 'MATTHEW CUNNINGHAM',
 'BOBBY CARSON',
 'MELINDA WILSON',
 'NANCY HANSEN',
 'GREGORY WALLS',
 'AMBER NIXON',
 'KRISTIN FRANCO',
 'JEREMIAH VAZQUEZ',
 'ANTHONY SMITH',
 'VICTORIA BRADY',
 'ERIN CLARK',
 'HEATHER BOYLE',
 'ELIZABETH SHEPPARD',
 'ROBERT BOONE',
 'GEOFFREY DANIELS',
 'JOHN KHAN',
 'CHRISTOPHER ARMSTRONG',
 'JENNIFER LOPEZ',
 'MELISSA ROBERTSON',
 'LISA FRANKLIN',
 'KRISTIN BURTON',
 'CAITLIN ADAMS',
 'EVAN HERNANDEZ',
 'JENNIFER KNIGHT',
 'BONNIE WILSON',
 'KENNETH RAMIREZ',
 'ELLEN MCCULLOUGH',
 'THOMAS STONE',
 'KATHLEEN ARMSTRONG',
 'TERRY BENNETT',
 'KRISTIN NGUYEN',
 'ANGELA RANDOLPH',
 'CHRISTOPHER TATE',
 'CHRISTOPHER WALTON',
 'MEAGAN MIRANDA',
 'DAVID BROWN',
 'ERIC MILLER',
 'JOEL BARTLETT',
 'STACY GILLESPIE',
 'CINDY SHAW',
 'ANDREW ERICKSON',
 'ASHLEY RODRIGUEZ',
 'DARRYL CRUZ',
 'SHEILA CHURCH',
 'NANCY MUNOZ',
 'REBECCA MARTINEZ',
 'JOHN SIMMONS',
 'LANCE TORRES',
 'TIMOTHY TERRY',
 'JOHN MOORE',
 'BRADLEY RAMOS',
 'JILL TAYLOR',
 'KELLY BROWN',
 'JONATHAN CHAVEZ',
 'DENISE WALL',
 'TODD MARTINEZ',
 'JENNIFER FORD',
 'RAYMOND PARK JR.',
 'JULIA REYNOLDS',
 'JOHN MCLEAN',
 'KATIE HOWARD',
 'AMANDA LAWSON',
 'PAUL MURRAY',
 'JAMES MORRIS',
 'MATTHEW COLLINS',
 'SHARON CARPENTER',
 'MARCUS BROWN',
 'MITCHELL DECKER',
 'DONALD MURPHY',
 'JOSEPH FARLEY',
 'BRENDAN PARKER',
 'SAMUEL DAVIS',
 'KELSEY PORTER',
 'MARK BRYANT',
 'MARGARET ZAMORA',
 'DAVID PAYNE',
 'TONY SALAS PHD',
 'ADRIAN BOWMAN',
 'MRS. LAUREN MORGAN',
 'JOSHUA MURRAY',
 'JASON WEBER',
 'REBECCA LEWIS',
 'JOAN ARCHER',
 'BRITTANY EDWARDS',
 'TIMOTHY DIAZ',
 'DANIEL BLANKENSHIP',
 'MARY STEPHENS',
 'BRIAN FIGUEROA',
 'STEPHANIE ANDERSON',
 'MICHAEL DOYLE',
 'KATHLEEN MARSHALL',
 'DONALD LYNCH',
 ...]

In [49]:
data['Name'] = (
    data['Name']
    .str.upper()
    .str.replace(r'\b(MRS|MR|MS|DR)\.?\s*', '', regex=True)
    .str.strip()
)

In [50]:
data['Name'].unique().tolist()

['BOBBY JACKSON',
 'LESLIE TERRY',
 'DANNY SMITH',
 'ANDREW WATTS',
 'ADRIENNE BELL',
 'EMILY JOHNSON',
 'EDWARD EDWARDS',
 'CHRISTINA MARTINEZ',
 'JASMINE AGUILAR',
 'CHRISTOPHER BERG',
 'MICHELLE DANIELS',
 'AARON MARTINEZ',
 'CONNOR HANSEN',
 'ROBERT BAUER',
 'BROOKE BRADY',
 'NATALIE GAMBLE',
 'HALEY PERKINS',
 'JAMIE CAMPBELL',
 'LUKE BURGESS',
 'DANIEL SCHMIDT',
 'TIMOTHY BURNS',
 'CHRISTOPHER BRIGHT',
 'KATHRYN STEWART',
 'EILEEN THOMPSON',
 'PAUL HENDERSON',
 'PETER FITZGERALD',
 'CATHY SMALL',
 'KENNETH MOORE',
 'MARY HUNTER',
 'JOSHUA OLIVER',
 'THOMAS MARTINEZ',
 'JAMES PATTERSON',
 'WILLIAM COOPER',
 'ERIN ORTEGA',
 'NICOLE RODRIGUEZ',
 'DAVID ANDERSON',
 'DENISE TORRES',
 'CASSANDRA ROBINSON',
 'NICOLE LUCERO',
 'PAMELA FERNANDEZ',
 'CHRISTOPHER LEE',
 'THOMAS MORSE',
 'ERIC LANE',
 'KATHERINE SMITH',
 'PAUL WILLIAMS',
 'LYNN MARTINEZ',
 'CHRISTOPHER CHAPMAN',
 'CHRIS FRYE',
 'KYLE BENNETT',
 'BRANDON COLLINS',
 'MICHAEL LIU',
 'STEPHANIE KENT',
 'JESSE BANKS',
 'PEGGY LEE',
 'TAMARA HERNANDEZ',
 'DAVID PIERCE MD',
 'BETHANY MOORE',
 'MICHAEL MILLS',
 'KYLE WILEY',
 'JACQUELINE JORDAN',
 'ASHLEY GUTIERREZ',
 'KIM SCOTT',
 'TRAVIS CARTER',
 'LARRY RODGERS',
 'NANCY GLOVER',
 'JESSICA KING',
 'CHRISTOPHER GONZALEZ',
 'JOHN HARTMAN',
 'MICHAEL MILLER',
 'ERICA MYERS',
 'CAROL PATTERSON',
 'JOSE LOPEZ',
 'KEVIN SIMMONS JR.',
 'DUANE HANEY',
 'JONATHAN YATES',
 'JOHN THOMAS',
 'ADRIAN BUCKLEY',
 'APRIL SANTIAGO',
 'DIANE SCHULTZ',
 'TIMOTHY MYERS',
 'NICOLE HUGHES',
 'CHAD MORENO',
 'SEAN JENNINGS',
 'DIANE BRANCH',
 'CINDY OROZCO',
 'PATRICIA MEDINA',
 'KAYLA PADILLA',
 'JUAN KLEIN',
 'WILLIAM HILL',
 'CARL BEST',
 'TINA GRIFFIN',
 'TYLER TAYLOR PHD',
 'TAYLOR HOWELL DDS',
 'MICHAEL MARTIN',
 'HEATHER MILLER',
 'CATHERINE GARDNER',
 'ANNE THOMPSON',
 'TODD COOPER',
 'PHILLIP LYONS',
 'MARK FORD',
 'MARCUS ZAMORA',
 'KATIE HENRY',
 'WILLIAM MORTON',
 'KATRINA MARTIN',
 'HUNTER MCKAY',
 'DWAYNE DAVIS',
 'SARAH CALDWELL',
 'DAVID HIGGINS',
 'BRADLEY COMBS',
 'CHRISTINA SCHMITT',
 'COLTON STRONG',
 'MARK PRICE',
 'SUZANNE SCHNEIDER',
 'MICHAEL HURLEY',
 'LINDSEY LAMBERT',
 'REBECCA PARSONS',
 'JUDY JOHNSON',
 'TONYA CAMPBELL',
 'JAMES ROSS',
 'SARA COOK',
 'ANNE HOWELL',
 'RENEE BAILEY',
 'JEFFREY TURNER',
 'LAUREN CLARK DDS',
 'TERRY THOMAS',
 'JASON BAKER',
 'JESSICA GUTIERREZ',
 'COURTNEY HODGES',
 'ANTHONY REYES',
 'LEAH CROSS DDS',
 'PAUL MARTINEZ',
 'DENISE RODRIGUEZ',
 'ASHLEY ERICKSON',
 'SEAN CARDENAS',
 'ALAN ALVAREZ',
 'JESSICA PHILLIPS',
 'TIMOTHY COLEMAN',
 'CHRISTINA WOODS',
 'MELISSA SCOTT',
 'GARY HOPKINS',
 'APRIL VALENCIA',
 'RITA ARCHER',
 'KIM PENA',
 'JASON FOLEY',
 'SHAUN GUZMAN',
 'MATTHEW WHITE',
 'ALEXIS WILSON',
 'JACQUELINE MARSHALL',
 'ROBERT HIGGINS',
 'SIERRA MORTON',
 'NATALIE STANTON',
 'JESSICA ACEVEDO',
 'JENNIFER MCMILLAN',
 'CHRISTOPHER MCCLAIN',
 'KEVIN HICKS',
 'MELINDA RICHARDS',
 'ROBYN MIRANDA',
 'SCOTT CASTILLO',
 'JOHN GARCIA',
 'MICHAEL TAYLOR',
 'JEFFREY WOOD',
 'MICHAEL SMITH',
 'WILLIAM GRIFFITH',
 'CHRISTINA LAWRENCE',
 'JESSICA HOLMES',
 'TRACEY GREENE',
 'AMANDA LOPEZ',
 'LAURA PETERS',
 'LAUREN ANDERSON',
 'WILLIAM CAMPOS',
 'JESSICA GONZALES',
 'BRUCE GONZALES',
 'ROBERT WALSH',
 'LISA LEWIS',
 'WILLIAM RUIZ',
 'STEVEN BALDWIN',
 'MEGAN COLON',
 'KIMBERLY BROOKS',
 'EDWARD SMITH JR.',
 'ALLISON CORDOVA',
 'LINDA THOMAS',
 'PARKER MOORE',
 'TANYA SOTO',
 'MICHAEL JORDAN',
 'CHRISTINA MARTIN',
 'TRACY BURKE',
 'DAVID SPENCE',
 'JOSEPH FOSTER',
 'NICHOLAS HALL',
 'CHRISTINA MACIAS',
 'SCOTT JONES',
 'JAMES ANDERSON',
 'SHAUN LONG',
 'KRISTINA MORA',
 'JOSHUA RICHMOND',
 'MARK LAWRENCE',
 'JOHN ELLIS',
 'TIFFANY DENNIS',
 'CYNTHIA HUANG',
 'MELISSA LAWRENCE',
 'STEVEN GOODWIN',
 'MARY HUNT',
 'ERIC RIVERA',
 'ALAN TAYLOR',
 'MICHAEL CAMPBELL',
 'ASHLEY WEBB DDS',
 'SHANNON BROWN',
 'LAWRENCE SHEPHERD',
 'SCOTT WADE',
 'HEATHER CURTIS',
 'KEVIN JEFFERSON',
 'DAVID GRIFFIN',
 'GRANT GEORGE',
 'ERIC STEWART',
 'ROBERT PITTMAN',
 'SYDNEY CROSS',
 'DAVID CRAWFORD',
 'LEAH AKE',
 'DIANA HALL',
 'JUSTIN LE',
 'KAREN PRICE DDS',
 'CAROLYN STEELE',
 'LAUREN RAMIREZ',
 'JACOB NEWMAN',
 'KATHERINE BARNETT',
 'JODI MARTINEZ',
 'ANDREA ALLEN',
 'NOAH BAXTER',
 'HECTOR MAXWELL',
 'HOLLY WALTERS',
 'JOSEPH SMITH',
 'ALBERT THOMAS',
 'JEFFERY WILLIAMSON',
 'JONATHAN MEADOWS',
 'KRISTIN BENNETT',
 'JOSEPH CARPENTER',
 'LARRY MAYER',
 'CLAYTON PETERSON',
 'DONALD ALVAREZ',
 'SARAH LEE',
 'JOHN PEREZ',
 'TIMOTHY JACOBS',
 'NATHAN SMALL',
 'DUSTIN WRIGHT',
 'JACOB WILLIAMS',
 'WILLIAM MCCOY',
 'MATTHEW WILKINS',
 'JOSEPH GONZALEZ',
 'ROBERT FIELDS',
 'LAWRENCE MIRANDA',
 'MITCHELL CARROLL',
 'CODY NICHOLS',
 'KELLI THOMPSON',
 'DANIELLE LOPEZ',
 'MELINDA JONES',
 'KRISTIN SMITH',
 'STEPHANIE REYNOLDS',
 'ANNA NORMAN',
 'MARIA HAYES',
 'TONYA RILEY MD',
 'REGINA DUNN',
 'MICHAEL JACOBS',
 'JASON MOORE MD',
 'ERIC HALL',
 'MALIK MARTINEZ',
 'LISA KENNEDY',
 'KRISTIN OCHOA',
 'JOSEPH ZUNIGA',
 'KYLE TYLER',
 'ERIC DUNCAN',
 'RACHEL ROMERO',
 'MICHAEL ANDERSON',
 'EMILY CLARK',
 'DANIEL MCKINNEY',
 'BONNIE WILLIAMS',
 'MARCUS HENRY',
 'KATHERINE HART',
 'MICHELLE PIERCE',
 'JULIE MEJIA',
 'CAMERON SANCHEZ',
 'DAVID VINCENT',
 'MELISSA GOMEZ',
 'AMANDA PONCE',
 'CAROL GOMEZ',
 'CHRISTOPHER PALMER',
 'PAUL HAHN',
 'ASHLEY MOORE',
 'LINDA HAMILTON',
 'ROBIN COX',
 'ANTHONY HALL',
 'ROBERT SMITH',
 'DEREK CARTER',
 'HEATHER MAY',
 'PETER GONZALEZ',
 'CHRIS FLETCHER',
 'SHIRLEY WILKINSON',
 'COURTNEY FARRELL',
 'ANDREA WILLIS',
 'CHAD HUFF',
 'DEVIN GILBERT',
 'DONALD DAVIS',
 'KURT MURPHY',
 'SYLVIA WEST',
 'DONALD VAZQUEZ',
 'REBECCA RUSH',
 'CHRISTOPHER CURRY',
 'MICHAEL EDWARDS',
 'CHRISTOPHER ARNOLD',
 'RACHEL HICKMAN',
 'ASHLEY GRAY',
 'ELIZABETH PEREZ',
 'ANGEL RANDOLPH DDS',
 'MARK SAUNDERS',
 'CHRISTIAN LANG',
 'PAM PERKINS',
 'KAYLA GREENE',
 'MICHAEL DAVID',
 'ALEXIS MCCALL',
 'BRANDON PEREZ MD',
 'JEFFREY COLE',
 'MATTHEW BROWN',
 'ROBERT SEXTON',
 'ASHLEY VASQUEZ',
 'MICHELLE FLYNN',
 'STEVEN TRAN',
 'JAMES MILLER',
 'BONNIE HILL',
 'ANTHONY DAVIS',
 'DAVID SHEPPARD',
 'JODI LANG',
 'VANESSA TAYLOR',
 'WAYNE LYNCH',
 'YESENIA MCFARLAND',
 'KENNETH WILSON',
 'JILLIAN MARKS',
 'MICHELLE CRUZ DDS',
 'CLARENCE FORD JR.',
 'DONALD KANE',
 'ZACHARY LARSEN',
 'SHERYL MARTINEZ',
 'NATHAN AVILA',
 'ANNE ANTHONY',
 'HOLLY LAMBERT',
 'JAMES RASMUSSEN',
 'SARAH CANNON',
 'MELINDA TANNER',
 'LAURIE JOSEPH',
 'STEPHANIE HUNTER',
 'GINA DAVIS',
 'CHRISTOPHER SHEA JR.',
 'SABRINA BALL',
 'JOYCE MCCORMICK',
 'DEVIN BELL',
 'ALLISON RAMIREZ',
 'LAURA ROMERO',
 'TONI FAULKNER',
 'PATRICIA TURNER',
 'NATHAN RAY',
 'RYAN SANCHEZ',
 'THOMAS DENNIS',
 'TIMOTHY FLORES',
 'WENDY LEVINE',
 'NICOLE GONZALEZ',
 'MICHAEL ELLISON',
 'BRANDON DAVIS',
 'VANESSA GARCIA',
 'AUTUMN PECK',
 'NATHANIEL REYNOLDS',
 'JOYCE MOODY',
 'MARK FUENTES',
 'BRETT FERGUSON',
 'TRAVIS SIMMONS',
 'JEREMY FRYE',
 'CAMERON MILLER',
 'WILLIAM WILLIAMS DDS',
 'TRACIE WRIGHT',
 'DAVID REYES',
 'PAIGE KING',
 'JAMES GARCIA',
 'LORI HARVEY',
 'AMY WANG',
 'JORDAN VARGAS',
 'GORDON KELLY',
 'NATHAN SCOTT',
 'LISA GREEN',
 'AMY COMBS',
 'KELLY SANFORD',
 'JESSICA BLACK MD',
 'ROBERT GOULD',
 'CHRISTINE VARGAS',
 'BARBARA DIAZ',
 'JOHN WASHINGTON',
 'DEVIN STEWART',
 'JAMES ROBERTS',
 'JAMES YATES',
 'PETER NICHOLS',
 'KAREN PRICE',
 'CHRISTOPHER JONES',
 'LARRY LEONARD',
 'MICHELLE ZHANG',
 'KRISTEN FLORES',
 'MATTHEW BELL',
 'BRADLEY MIRANDA',
 'CHRISTOPHER MOORE',
 'DAN PINEDA',
 'MARIAH SMITH',
 'SABRINA COOK',
 'MELISSA HOFFMAN',
 'JOSEPH MARTIN',
 'MELISSA SIMS',
 'SARAH EVANS',
 'MARIA ANDERSON',
 'MARIA JOHNSTON',
 'JAMES COLE',
 'ISAIAH HOLT',
 'JOSEPH GONZALES',
 'JENNIFER CAMACHO',
 'HECTOR JONES',
 'JESSICA JONES DDS',
 'ISABELLA MARTIN',
 'DANIEL PALMER',
 'STEPHANIE BENSON',
 'ASHLEY WILLIAMS',
 'GREGORY NGUYEN',
 'JOE SMITH',
 'LISA WATTS',
 'ALEXANDER GARCIA',
 'ELIZABETH PERKINS',
 'LAURA WELLS',
 'ROBERT MCCORMICK',
 'MICHAEL YU',
 'JACOB GRAHAM',
 'ANDREA KENNEDY',
 'STACEY ANDERSON',
 'JASON MARSH',
 'TIFFANY FERGUSON',
 'MARK HERNANDEZ',
 'KEITH HENRY',
 'MICHELLE WRIGHT',
 'TROY DAVIS',
 'MISTY BURTON',
 'ROBERT ROBINSON',
 'CHRISTINA CALDERON',
 'JOHN GRAHAM',
 'MICHAEL PARKER',
 'WILLIAM EVANS',
 'VALERIE HODGES',
 'BRENDA BECK',
 'CHRISTINE DAVIS',
 'KEVIN DANIEL',
 'BRITTNEY WAGNER',
 'CRISTIAN BUCHANAN',
 'MICHAEL BRADY',
 'JORDAN LEON',
 'KATELYN CUNNINGHAM',
 'KRYSTAL MENDOZA',
 'ALEX RODRIGUEZ',
 'GEOFFREY BARKER',
 'ALEC MITCHELL',
 'JASON JORDAN',
 'PHILIP REYES',
 'AARON BRADSHAW',
 'ERICA FORD',
 'KATIE BARRETT DVM',
 'JACOB YOUNG',
 'AMY RAMOS',
 'PATRICK MORALES',
 'SOPHIA CONWAY',
 'JAMES MOORE',
 'CHRISTOPHER COCHRAN',
 'ROBERT CARTER',
 'MORGAN NGUYEN',
 'NATHAN MONTOYA',
 'JOE BERRY PHD',
 'DANIEL ORTIZ',
 'MATTHEW CLARK',
 'JACQUELINE HARDY',
 'EMILY JOSEPH',
 'SARAH HICKS',
 'BRIANA ROSS',
 'MARY MCCULLOUGH',
 'BRIAN OSBORNE',
 'SUSAN WALTERS',
 'CATHERINE HARVEY',
 'CORY PIERCE',
 'JESUS JORDAN',
 'ANN DUNCAN',
 'SARAH PORTER',
 'JACQUELINE DEAN',
 'ANNE LAM',
 'JENNIFER GOMEZ',
 'DAVID CURTIS',
 'JOSHUA JOHNSON',
 'JEREMY BOWEN',
 'DENNIS CLARKE',
 'JENNIFER SPENCE',
 'BILLY FITZGERALD',
 'KRISTEN JAMES',
 'CAITLIN BENDER',
 'BRENDA FULLER',
 'CASSANDRA RICE',
 'SERGIO SANCHEZ',
 'KEVIN STEIN',
 'MAUREEN GRANT MD',
 'SAMANTHA GUTIERREZ',
 'GEORGE WOODWARD',
 'SHANE TATE',
 'KERRY HAWKINS',
 'MARISSA MORA',
 'RICKY MEYER',
 'EDWARD JONES JR.',
 'HEATHER MELENDEZ',
 'JESSICA MACIAS',
 'JAMIE LEACH',
 'MATTHEW SIMMONS',
 'SHEILA BAXTER',
 'DAVE PARRISH',
 'BRYAN STEWART',
 'JAMES BELL',
 'JOSHUA LOVE',
 'ROBERT CLARK',
 'MARISA GOLDEN',
 'NANCY HAMILTON',
 'BRYAN BOWERS',
 'NICOLE MARTIN',
 'WILLIAM HARMON',
 'TOM BROWN',
 'CYNTHIA NELSON',
 'TODD GROSS',
 'STEPHANIE CHUNG',
 'KAYLA PEREZ',
 'JOSHUA NELSON',
 'JAKE COPELAND',
 'MARIA GARDNER',
 'JANET ROBERTS DDS',
 'PETER RAMSEY',
 'ASHLEY FARMER',
 'KATHERINE HALE',
 'GARY BOWEN',
 'LAURA RYAN',
 'TIMOTHY LOPEZ',
 'ANTHONY GUZMAN',
 'MICHAEL SHARP',
 'DAVID CARROLL',
 'CONNOR BARTON',
 'ANGELA SCOTT',
 'DAVID ORTIZ',
 'PATRICK PIERCE',
 'KEITH JOHNSON',
 'ANTONIO SMITH',
 'JOHN TAYLOR',
 'BARBARA STEWART',
 'LARRY TANNER',
 'MALLORY DIAZ',
 'JOHN WILLIAMS',
 'PETER MILLER',
 'RYAN BUTLER',
 'SAMANTHA LOWERY',
 'TIFFANY LEE',
 'SAMANTHA WILLIS',
 'PAMELA BROWN',
 'CARLA WALKER',
 'MARY GONZALES',
 'SHELLEY FLEMING',
 'MARK BLAKE',
 'SCOTT KING',
 'JESSICA DAVIS',
 'ANTHONY ODOM',
 'CHARLES BROWN',
 'RACHEL DAVIS',
 'SANDRA MCCALL',
 'NICOLE FRANCIS',
 'STEVEN SMITH',
 'KAREN JOHNSON',
 'ANNA ROGERS',
 'PRISCILLA DECKER',
 'TREVOR WRIGHT',
 'WILLIAM TUCKER',
 'JESSICA KELLER',
 'WILLIAM HENRY',
 'ROBIN CLARKE',
 'JESSICA GARZA',
 'JAMIE SALAZAR',
 'STEVEN VAUGHAN',
 'MICHAEL CONTRERAS',
 'ALLEN ROBERTS',
 'AMY POWELL',
 'KENNETH SMITH',
 'MATTHEW WEST',
 'ERIK MONTOYA',
 'AUSTIN LEWIS',
 'KENNETH THOMPSON',
 'AMANDA DURHAM',
 'STEPHEN HUDSON',
 'CASSANDRA VELAZQUEZ',
 'SUSAN PENA',
 'ANTHONY PERKINS',
 'KATRINA LOPEZ',
 'BRIAN FOSTER',
 'JASON THOMPSON',
 'DAVID AYALA',
 'JARED YODER',
 'GREGORY CANNON',
 'LISA ANDERSON',
 'ELIZABETH SHIELDS',
 'PATRICIA KIM',
 'JESSICA SOTO',
 'JENNY REYNOLDS',
 'SHANNON BARRETT',
 'TERRI PERRY',
 'JOSEPH MADDEN',
 'REBECCA HOGAN',
 'KELLY WALKER',
 'JULIA MUELLER',
 'KAYLA MOORE',
 'KAITLYN SMITH',
 'DANIEL KEMP',
 'LAURA MYERS',
 'CAROL REED',
 'JESSICA CARTER',
 'VANESSA SCHAEFER',
 'MIGUEL GOMEZ',
 'LINDA CARDENAS',
 'ANNETTE JAMES',
 'SUSAN HURLEY',
 'CAROLYN WADE',
 'ANGELA DELEON',
 'CAROLYN COOPER',
 'REBECCA HARRIS',
 'GARY CURTIS',
 'RYAN LIU',
 'DENNIS MORROW',
 'JENNIFER COOPER',
 'JACOB LOPEZ',
 'CAROL MCCLAIN',
 'MICHAEL RICHARDSON',
 'MARK NGUYEN',
 'ERIC COOK',
 'KRISTEN STEPHENS',
 'DANA WALTON',
 'SCOTT ARNOLD',
 'MEGAN WHEELER',
 'AARON COX',
 'CASSANDRA MARTINEZ',
 'SHAWN BROWN',
 'SANDRA WILLIAMSON',
 'JENNIFER STEPHENS',
 'STEPHANIE RODRIGUEZ',
 'CAROLINE MCINTYRE',
 'CAMERON ROBINSON',
 'TAMMY PINEDA',
 'NATALIE ANDERSON',
 'JASMINE RODRIGUEZ',
 'DEBRA MCKEE',
 'SANDRA GREENE',
 'CRYSTAL MORRIS',
 'JASON PARKER',
 'ROY JONES',
 'RICHARD ANDERSON',
 'JENNIFER FOSTER',
 'DEBBIE WILSON',
 'TRAVIS FLORES',
 'EMILY YOUNG',
 'SANDY HALL',
 'MADISON WRIGHT',
 'AMY MANN',
 'JASON STEELE',
 'PAMELA MIDDLETON',
 'LISA JACKSON',
 'SAMANTHA PATEL',
 'HERBERT RODRIGUEZ',
 'OLIVIA POWELL',
 'SAMANTHA PERKINS',
 'MICHAEL POTTS',
 'KERRY HERNANDEZ',
 'JOSHUA REYES',
 'JENNIFER ORTEGA',
 'BRITTANY BRAUN',
 'DANIEL CHEN',
 'ERICA HART',
 'ALICIA SCOTT',
 'AMANDA AGUIRRE',
 'MARK HICKS',
 'TIMOTHY DAVIS',
 'LONNIE DOMINGUEZ',
 'KIMBERLY HALE',
 'DANA WILLIAMSON',
 'GEORGE BROWN JR.',
 'ALLEN CAMACHO',
 'NATHAN WOODS',
 'CATHERINE SMITH',
 'JERRY LEE',
 'ALEXANDER COLEMAN',
 'DAVID JENSEN',
 'DEBORAH EVANS',
 'ALEXANDRIA COLON',
 'SAMUEL HANSON',
 'BRYAN PHILLIPS',
 'NATHAN WILEY',
 'ALISHA MURPHY',
 'AMANDA LUCERO',
 'SHEILA SELLERS',
 'SUSAN CHAN',
 'ANGEL MITCHELL',
 'DARLENE COHEN',
 'KRISTY ONEILL',
 'SHERRI GARCIA',
 'MICHAEL WEBER',
 'BETH SCHWARTZ',
 'CYNTHIA CLARKE',
 'MARK GILES',
 'TAMARA BELTRAN',
 'JOSEPH GUTIERREZ',
 'JAMIE JIMENEZ',
 'CHARLES MURPHY',
 'CARLOS LOPEZ',
 'JOHNNY IRWIN',
 'SCOTT WERNER',
 'TERRI STEWART',
 'DAVID DAVIS',
 'STEPHEN HARRIS',
 'BRIDGET ADAMS',
 'MICHAEL MORTON',
 'MICHELLE LIU',
 'REGINA BRIGHT',
 'SAMUEL DECKER',
 'PAUL WRIGHT',
 'BRIAN OLSON',
 'TRACEY HARRISON',
 'ERIKA JOHNSON',
 'PETER CUNNINGHAM',
 'SIERRA WHITE',
 'EDDIE RUSSO DVM',
 'YVETTE TURNER',
 'JAMES CHARLES',
 'ALEXIS ALLEN',
 'STEPHANIE MARTIN',
 'SHELBY ANDERSON',
 'ABIGAIL FARMER',
 'CHRISTINA MILLER',
 'MATTHEW WYATT',
 'DAVID MONTOYA',
 'ERIC PARK',
 'LORI TREVINO',
 'DWAYNE CASTILLO',
 'KRISTINE MCCALL',
 'JOSEPH SELLERS',
 'DONALD ANDERSON',
 'VICTORIA WILLIAMS',
 'ANNA JONES',
 'ROBERT DAVIS',
 'JEFFREY HALL',
 'TERRY GRAVES',
 'JEROME MORALES',
 'KEITH RODRIGUEZ',
 'TAMARA DAVENPORT',
 'JONATHAN SIMON',
 'HOLLY ARMSTRONG',
 'RONALD BANKS',
 'RYAN BRADFORD DDS',
 'JANICE HALL',
 'JACOB MCDONALD',
 'GLENN MASSEY',
 'SANDRA MURRAY',
 'MARK WILLIAMS',
 'STEPHANIE REID DVM',
 'SETH BARTLETT II',
 'JEREMY RICH',
 'ELIZABETH MILLER',
 'ERIN MARTIN',
 'FRANK HESS',
 'PAUL ROGERS',
 'JENNIFER EDWARDS',
 'BRIAN HALL',
 'KIMBERLY WILLIAMS',
 'ISAAC MENDEZ',
 'SARAH SMITH',
 'DANIEL WOLF',
 'ROBERT ROSS',
 'DOUGLAS FOSTER',
 'LOUIS LOWERY',
 'JESSICA TYLER',
 'WILLIAM DAVIES',
 'JESSICA REYES',
 'DANIEL JONES',
 'PAULA MORALES',
 'DAVID SPEARS',
 'SCOTT BERRY',
 'DALTON NGUYEN',
 'SCOTT CLARK',
 'JAMIE BAKER',
 'COURTNEY PATRICK',
 'WILLIAM WARE',
 'AMBER ANDERSON',
 'CASEY JOHNSON',
 'ZACHARY COLLINS',
 'ZACHARY REED',
 'CHRISTOPHER WEISS',
 'CHARLES STRONG',
 'KATHERINE KELLY',
 'CHRISTOPHER HENDERSON',
 'JOSEPH BROWN',
 'JOSEPH SANCHEZ',
 'KYLE PEREZ',
 'EDUARDO HOUSTON',
 'LORI ROACH',
 'ERIC BUTLER',
 'JEFFREY BROWN',
 'THOMAS HAAS',
 'KELLY TURNER',
 'LANCE SIMPSON',
 'JEFFREY GREEN',
 'ERIC COLLINS',
 'BRIANNA WILLIAMS',
 'ROBERT GRAVES',
 'CINDY WILLIAMS',
 'VICTOR SULLIVAN',
 'FRANK SCOTT',
 'MARK BRADSHAW',
 'JESSICA DUNN',
 'KELSEY FOX',
 'MARY RICE',
 'RACHEL JACKSON',
 'LEAH FREDERICK',
 'CONNOR ODONNELL',
 'CLAUDIA DOWNS',
 'WILLIAM LANG',
 'LISA MORAN',
 'RUBEN BURTON',
 'BRANDON SMITH',
 'JESSICA MURPHY',
 'MISTY WILLIAMS',
 'BRANDY GEORGE',
 'ANDREA BUCK',
 'STEPHANIE BURKE',
 'STEPHANIE MOON',
 'SHARON JOHNSON',
 'MATTHEW HALEY',
 'SABRINA MAY',
 'MELINDA AUSTIN',
 'ANGELA MONTGOMERY',
 'VANESSA MARTIN',
 'GABRIEL STEVENS',
 'MICHAEL WOLFE',
 'BROOKE TORRES',
 'VICTOR DUKE',
 'JOSEPH GARRETT',
 'KARA LI',
 'JUAN KELLEY',
 'SHAWNA RUSSELL',
 'LORI LAWRENCE',
 'WHITNEY JONES',
 'JOE DAVILA',
 'LISA KELLER',
 'JORDAN BUSH',
 'BRENDA YU',
 'JASMINE SHORT',
 'TAMARA LEONARD',
 'KEVIN WONG',
 'LISA LOPEZ',
 'JUSTIN VARGAS',
 'JODY LOPEZ',
 'JONATHAN WOODS',
 'EMMA RAY',
 'ANDREA JOHNSON',
 'WAYNE SHARP',
 'SHELBY BLACK',
 'MARTHA MARTIN',
 'AMANDA WILSON',
 'JEREMY NGUYEN',
 'EILEEN HARRIS',
 'JOHN BECKER',
 'FELICIA WILEY',
 'JESSE JONES',
 'STEVEN GLENN',
 'CAROLINE SWANSON',
 'TERRY NICHOLSON',
 'KELLY THOMAS',
 'STEVEN MCGEE',
 'SHELLEY WARE',
 'MELISSA BRADY',
 'MARIA HALL',
 'ANDRE SMITH',
 'KAREN GONZALEZ',
 'VINCENT SELLERS',
 'BRANDON BURKE',
 'MARK HANCOCK',
 'KENNETH PEREZ',
 'MARTIN HANSEN',
 'SUSAN BROWN',
 'NICOLE ALVARADO',
 'JESSICA RODRIGUEZ',
 'TINA PRICE',
 'JACK WILLIS',
 'GREGORY ADAMS',
 'DAVID ROBERTS',
 'CORY PERRY',
 'JESSICA BARRY',
 'CYNTHIA THOMAS',
 'SHANNON JOHNSON',
 'JUSTIN WHITE',
 'REGINA STEWART',
 'CHELSEA FINLEY',
 'EMMA BENNETT',
 'ALAN LEE',
 'KATELYN MILLER',
 'AMANDA MORRIS',
 'DAVID PRATT',
 'MATTHEW CUNNINGHAM',
 'BOBBY CARSON',
 'MELINDA WILSON',
 'NANCY HANSEN',
 'GREGORY WALLS',
 'AMBER NIXON',
 'KRISTIN FRANCO',
 'JEREMIAH VAZQUEZ',
 'ANTHONY SMITH',
 'VICTORIA BRADY',
 'ERIN CLARK',
 'HEATHER BOYLE',
 'ELIZABETH SHEPPARD',
 'ROBERT BOONE',
 'GEOFFREY DANIELS',
 'JOHN KHAN',
 'CHRISTOPHER ARMSTRONG',
 'JENNIFER LOPEZ',
 'MELISSA ROBERTSON',
 'LISA FRANKLIN',
 'KRISTIN BURTON',
 'CAITLIN ADAMS',
 'EVAN HERNANDEZ',
 'JENNIFER KNIGHT',
 'BONNIE WILSON',
 'KENNETH RAMIREZ',
 'ELLEN MCCULLOUGH',
 'THOMAS STONE',
 'KATHLEEN ARMSTRONG',
 'TERRY BENNETT',
 'KRISTIN NGUYEN',
 'ANGELA RANDOLPH',
 'CHRISTOPHER TATE',
 'CHRISTOPHER WALTON',
 'MEAGAN MIRANDA',
 'DAVID BROWN',
 'ERIC MILLER',
 'JOEL BARTLETT',
 'STACY GILLESPIE',
 'CINDY SHAW',
 'ANDREW ERICKSON',
 'ASHLEY RODRIGUEZ',
 'DARRYL CRUZ',
 'SHEILA CHURCH',
 'NANCY MUNOZ',
 'REBECCA MARTINEZ',
 'JOHN SIMMONS',
 'LANCE TORRES',
 'TIMOTHY TERRY',
 'JOHN MOORE',
 'BRADLEY RAMOS',
 'JILL TAYLOR',
 'KELLY BROWN',
 'JONATHAN CHAVEZ',
 'DENISE WALL',
 'TODD MARTINEZ',
 'JENNIFER FORD',
 'RAYMOND PARK JR.',
 'JULIA REYNOLDS',
 'JOHN MCLEAN',
 'KATIE HOWARD',
 'AMANDA LAWSON',
 'PAUL MURRAY',
 'JAMES MORRIS',
 'MATTHEW COLLINS',
 'SHARON CARPENTER',
 'MARCUS BROWN',
 'MITCHELL DECKER',
 'DONALD MURPHY',
 'JOSEPH FARLEY',
 'BRENDAN PARKER',
 'SAMUEL DAVIS',
 'KELSEY PORTER',
 'MARK BRYANT',
 'MARGARET ZAMORA',
 'DAVID PAYNE',
 'TONY SALAS PHD',
 'ADRIAN BOWMAN',
 'LAUREN MORGAN',
 'JOSHUA MURRAY',
 'JASON WEBER',
 'REBECCA LEWIS',
 'JOAN ARCHER',
 'BRITTANY EDWARDS',
 'TIMOTHY DIAZ',
 'DANIEL BLANKENSHIP',
 'MARY STEPHENS',
 'BRIAN FIGUEROA',
 'STEPHANIE ANDERSON',
 'MICHAEL DOYLE',
 'KATHLEEN MARSHALL',
 'DONALD LYNCH',
 ...]